Dedicated AAGUID Type
swift-server/swift-webauthn pull request #58
Opened 2024-03-25 12:22 UTC by dimitribouniol

As I was implementing the client, I found it useful to have a type for Authenticator Attestation Globally Unique IDs (AAGUIDs) since AAGUIDs are defined as 16-byte IDs, which prevents passing in the wrong-sized values. Internally, I have this wrapping a UUID since they are conceptually similar. Some questions before we consider merging this though:
- The name: `AuthenticatorAttestationGloballyUniqueID` is clearly more descriptive, though `AAGUID` is defined as a type alias. Similarly, the property names are now spelled out, but I kept `aaguid` for things like local variables.
- Codable for this type falls back to the UUID representation (hex string with dashes), but I can see base64-urlencoded or straight hex as equally good alternatives. This is Codable because `AttestedCredentialData` (and by extension `AuthenticatorData`) are, but not sure they need to be since authenticator data is represented in a binary form.

As a follow-up, would love to extend this to other bag-of-byte types like CredentialID.

2024-05-07 15:58 UTC, dimitribouniol commented on Sources/WebAuthn/Helpers/ByteCasting.swift
> +extension BidirectionalCollection where Element == UInt8 {
This one is used during parsing in `AuthenticatorData.swift` line 87 (via AAGUID's initializer), and simplifies the conversion between bytes and trivial types like primitives, tables, and structs of those. In fact, we can use this to also drop the questionable re-implementation of endianness correction we have here in favor of using built-ins on UInt8/16/32/64 and friends (I have a follow-up PR based on this one that does that cleanup).

Here, `BidirectionalCollection` is used so this helper applies not only to `[UInt8]`, but also slices and other spans without needing to operate on a copy of the whole array first. This implementation actually comes from a [library](https://github.com/mochidev/Bytes) I wrote that simplifies this whole thing, but I didn't see the need to depend on a whole library for essentially a 10 line function.

(This is also for internal use only — we shouldn't expose it publicly in this library)

2024-05-08 13:09 UTC, dimitribouniol commented on Sources/WebAuthn/Ceremonies/Registration/AttestedCredentialData.swift
> +    let authenticatorAttestationGloballyUniqueID: AAGUID
Done

2024-05-08 13:09 UTC, dimitribouniol commented on Sources/WebAuthn/Ceremonies/Shared/AuthenticatorAttestationGloballyUniqueID.swift
> +public struct AuthenticatorAttestationGloballyUniqueID: Hashable {
Done

2024-05-08 13:10 UTC, dimitribouniol commented on Sources/WebAuthn/Helpers/ByteCasting.swift
> +extension BidirectionalCollection where Element == UInt8 {
Here is the follow-up for integers: https://github.com/swift-server/webauthn-swift/pull/68/commits/df18fe6080e6abe3f86c85b40cb51b8dfd282632

2024-06-09 00:55 UTC, 0xTim requested changes
One nit then LGTM

2024-06-09 00:55 UTC, 0xTim commented on Sources/WebAuthn/Ceremonies/Shared/AuthenticatorAttestationGloballyUniqueID.swift
> +    public static let anonymous = AuthenticatorAttestationGloballyUniqueID(bytes: Array(repeating: 0, count: 16))!
Nit
```suggestion
    public static let anonymous = AuthenticatorAttestationGloballyUniqueID(bytes: Array(repeating: 0, count: Self.size))!
```

2024-06-11 12:37 UTC, dimitribouniol commented on Sources/WebAuthn/Ceremonies/Shared/AuthenticatorAttestationGloballyUniqueID.swift
> +    public static let anonymous = AuthenticatorAttestationGloballyUniqueID(bytes: Array(repeating: 0, count: 16))!
Good catch, fixed!

2024-09-10 14:44 UTC, 0xTim approved these changes

2024-09-10 15:45 UTC, merged